// Code generated by protoc-gen-go. DO NOT EDIT.
// source: base.proto

package base

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BaseMessage struct {
	// 消息头部
	Head string `protobuf:"bytes,1,opt,name=head,proto3" json:"head,omitempty"`
	// 消息内容
	Body                 *Body    `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BaseMessage) Reset()         { *m = BaseMessage{} }
func (m *BaseMessage) String() string { return proto.CompactTextString(m) }
func (*BaseMessage) ProtoMessage()    {}
func (*BaseMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_db1b6b0986796150, []int{0}
}

func (m *BaseMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BaseMessage.Unmarshal(m, b)
}
func (m *BaseMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BaseMessage.Marshal(b, m, deterministic)
}
func (m *BaseMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseMessage.Merge(m, src)
}
func (m *BaseMessage) XXX_Size() int {
	return xxx_messageInfo_BaseMessage.Size(m)
}
func (m *BaseMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseMessage.DiscardUnknown(m)
}

var xxx_messageInfo_BaseMessage proto.InternalMessageInfo

func (m *BaseMessage) GetHead() string {
	if m != nil {
		return m.Head
	}
	return ""
}

func (m *BaseMessage) GetBody() *Body {
	if m != nil {
		return m.Body
	}
	return nil
}

type Head struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Head) Reset()         { *m = Head{} }
func (m *Head) String() string { return proto.CompactTextString(m) }
func (*Head) ProtoMessage()    {}
func (*Head) Descriptor() ([]byte, []int) {
	return fileDescriptor_db1b6b0986796150, []int{1}
}

func (m *Head) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Head.Unmarshal(m, b)
}
func (m *Head) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Head.Marshal(b, m, deterministic)
}
func (m *Head) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Head.Merge(m, src)
}
func (m *Head) XXX_Size() int {
	return xxx_messageInfo_Head.Size(m)
}
func (m *Head) XXX_DiscardUnknown() {
	xxx_messageInfo_Head.DiscardUnknown(m)
}

var xxx_messageInfo_Head proto.InternalMessageInfo

func (m *Head) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Body struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Body) Reset()         { *m = Body{} }
func (m *Body) String() string { return proto.CompactTextString(m) }
func (*Body) ProtoMessage()    {}
func (*Body) Descriptor() ([]byte, []int) {
	return fileDescriptor_db1b6b0986796150, []int{2}
}

func (m *Body) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Body.Unmarshal(m, b)
}
func (m *Body) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Body.Marshal(b, m, deterministic)
}
func (m *Body) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Body.Merge(m, src)
}
func (m *Body) XXX_Size() int {
	return xxx_messageInfo_Body.Size(m)
}
func (m *Body) XXX_DiscardUnknown() {
	xxx_messageInfo_Body.DiscardUnknown(m)
}

var xxx_messageInfo_Body proto.InternalMessageInfo

type ResponseCode struct {
	Retcode              int32    `protobuf:"varint,1,opt,name=retcode,proto3" json:"retcode,omitempty"`
	ErrorMessgae         string   `protobuf:"bytes,2,opt,name=error_messgae,json=errorMessgae,proto3" json:"error_messgae,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponseCode) Reset()         { *m = ResponseCode{} }
func (m *ResponseCode) String() string { return proto.CompactTextString(m) }
func (*ResponseCode) ProtoMessage()    {}
func (*ResponseCode) Descriptor() ([]byte, []int) {
	return fileDescriptor_db1b6b0986796150, []int{3}
}

func (m *ResponseCode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseCode.Unmarshal(m, b)
}
func (m *ResponseCode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseCode.Marshal(b, m, deterministic)
}
func (m *ResponseCode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseCode.Merge(m, src)
}
func (m *ResponseCode) XXX_Size() int {
	return xxx_messageInfo_ResponseCode.Size(m)
}
func (m *ResponseCode) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseCode.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseCode proto.InternalMessageInfo

func (m *ResponseCode) GetRetcode() int32 {
	if m != nil {
		return m.Retcode
	}
	return 0
}

func (m *ResponseCode) GetErrorMessgae() string {
	if m != nil {
		return m.ErrorMessgae
	}
	return ""
}

func init() {
	proto.RegisterType((*BaseMessage)(nil), "base.BaseMessage")
	proto.RegisterType((*Head)(nil), "base.Head")
	proto.RegisterType((*Body)(nil), "base.Body")
	proto.RegisterType((*ResponseCode)(nil), "base.ResponseCode")
}

func init() { proto.RegisterFile("base.proto", fileDescriptor_db1b6b0986796150) }

var fileDescriptor_db1b6b0986796150 = []byte{
	// 176 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x34, 0x8f, 0xb1, 0x0e, 0x82, 0x30,
	0x10, 0x40, 0x83, 0xa9, 0x18, 0x0e, 0x5c, 0x6e, 0x22, 0x0e, 0x86, 0xd4, 0x85, 0x89, 0x41, 0xbf,
	0x40, 0x5c, 0x5c, 0x58, 0xfa, 0x03, 0xa6, 0xd8, 0x0b, 0x2e, 0x70, 0xa4, 0xc7, 0xc2, 0xdf, 0x9b,
	0x96, 0xb0, 0xbd, 0xbe, 0xbc, 0xde, 0xe5, 0x00, 0x7a, 0x2b, 0xd4, 0xcc, 0x9e, 0x17, 0x46, 0x15,
	0x58, 0x3f, 0x21, 0x6f, 0xad, 0x50, 0x47, 0x22, 0x76, 0x20, 0x44, 0x50, 0x3f, 0xb2, 0xae, 0x4c,
	0xaa, 0xa4, 0xce, 0x4c, 0x64, 0xbc, 0x82, 0xea, 0xd9, 0xad, 0xe5, 0xa1, 0x4a, 0xea, 0xfc, 0x0e,
	0x4d, 0x9c, 0xd1, 0xb2, 0x5b, 0x4d, 0xf4, 0xfa, 0x02, 0xea, 0x1d, 0x3a, 0x04, 0x35, 0xd9, 0x91,
	0xf6, 0xbf, 0x81, 0x75, 0x0a, 0x2a, 0x94, 0xba, 0x83, 0xc2, 0x90, 0xcc, 0x3c, 0x09, 0xbd, 0xd8,
	0x11, 0x96, 0x70, 0xf2, 0xb4, 0x7c, 0xd9, 0x6d, 0xf9, 0xd1, 0xec, 0x4f, 0xbc, 0xc1, 0x99, 0xbc,
	0x67, 0xff, 0x19, 0x49, 0x64, 0xb0, 0x14, 0xd7, 0x66, 0xa6, 0x88, 0xb2, 0xdb, 0x5c, 0x9f, 0xc6,
	0x13, 0x1e, 0xff, 0x00, 0x00, 0x00, 0xff, 0xff, 0xee, 0x0d, 0x81, 0x5b, 0xd0, 0x00, 0x00, 0x00,
}
